paths:
  /read_file:
    post:
      operationId: readFile
      summary: Read a file from a specific path
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/readFileRequest'
      responses:
        "200":
          description: OK
components:
  schemas:
    readFileRequest:
      type: object
      required:
      - filepath
      properties:
        filepath:
          type: string
          description: The path of the file to read.
          required: true